// Mock data for development when database is unavailable

export const mockCountries = [
  { id: 1, nameEn: 'United States', nameFa: 'ایالات متحده', code: 'US', flagUrl: null, totalPosts: 5, createdAt: new Date() },
  { id: 2, nameEn: 'United Kingdom', nameFa: 'انگلستان', code: 'GB', flagUrl: null, totalPosts: 3, createdAt: new Date() },
  { id: 3, nameEn: 'Germany', nameFa: 'آلمان', code: 'DE', flagUrl: null, totalPosts: 4, createdAt: new Date() },
  { id: 4, nameEn: 'France', nameFa: 'فرانسه', code: 'FR', flagUrl: null, totalPosts: 2, createdAt: new Date() },
  { id: 5, nameEn: 'Japan', nameFa: 'ژاپن', code: 'JP', flagUrl: null, totalPosts: 6, createdAt: new Date() },
  { id: 6, nameEn: 'Canada', nameFa: 'کانادا', code: 'CA', flagUrl: null, totalPosts: 3, createdAt: new Date() },
  { id: 7, nameEn: 'Australia', nameFa: 'استرالیا', code: 'AU', flagUrl: null, totalPosts: 2, createdAt: new Date() },
  { id: 8, nameEn: 'India', nameFa: 'هند', code: 'IN', flagUrl: null, totalPosts: 4, createdAt: new Date() },
  { id: 9, nameEn: 'China', nameFa: 'چین', code: 'CN', flagUrl: null, totalPosts: 3, createdAt: new Date() },
]

export const mockCategories = [
  { id: 1, slug: 'work-culture', nameEn: 'Work Culture', nameFa: null, descriptionEn: 'How people show up, lead, and switch off at work.', descriptionFa: null, icon: '💼', displayOrder: 1, createdAt: new Date() },
  { id: 2, slug: 'food-culture', nameEn: 'Food Culture', nameFa: null, descriptionEn: 'Meal times, table manners, and what\'s polite to order.', descriptionFa: null, icon: '🍽️', displayOrder: 2, createdAt: new Date() },
  { id: 3, slug: 'family-life', nameEn: 'Family Life', nameFa: null, descriptionEn: 'Roles, closeness, and how households are run.', descriptionFa: null, icon: '👨‍👩‍👧‍👦', displayOrder: 3, createdAt: new Date() },
  { id: 4, slug: 'manners-etiquette', nameEn: 'Manners & Etiquette', nameFa: null, descriptionEn: 'Small courtesies that mean a lot.', descriptionFa: null, icon: '🤝', displayOrder: 4, createdAt: new Date() },
  { id: 5, slug: 'punctuality', nameEn: 'Punctuality', nameFa: null, descriptionEn: 'What "on time" actually means, day to day.', descriptionFa: null, icon: '⏰', displayOrder: 5, createdAt: new Date() },
  { id: 6, slug: 'hospitality', nameEn: 'Hospitality', nameFa: null, descriptionEn: 'How guests are welcomed and treated.', descriptionFa: null, icon: '🏠', displayOrder: 6, createdAt: new Date() },
  { id: 7, slug: 'driving-culture', nameEn: 'Driving Culture', nameFa: null, descriptionEn: 'Rules on paper vs. rules on the road.', descriptionFa: null, icon: '🚗', displayOrder: 7, createdAt: new Date() },
  { id: 8, slug: 'attitudes-to-strangers', nameEn: 'Attitudes to Strangers', nameFa: null, descriptionEn: 'How open or reserved people are with people they don\'t know.', descriptionFa: null, icon: '👥', displayOrder: 8, createdAt: new Date() },
  { id: 9, slug: 'dress-code', nameEn: 'Dress Code', nameFa: null, descriptionEn: 'What\'s expected, and what draws a stare.', descriptionFa: null, icon: '👔', displayOrder: 9, createdAt: new Date() },
]

export const mockPosts = [
  {
    id: '1',
    userId: 'user-1',
    countryId: 5,
    categoryId: 1,
    title: 'Punctuality is taken very seriously',
    content: 'In Japan, being even 5 minutes late is considered extremely rude. Trains run on time to the second, and meetings start exactly when scheduled. This cultural norm extends to all aspects of life.',
    experienceType: 'lived',
    likesCount: 24,
    dislikesCount: 2,
    commentsCount: 5,
    isPublished: true,
    isReported: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    user: { id: 'user-1', email: 'user1@example.com' },
    category: { id: 1, nameEn: 'Work Culture', icon: '💼' },
    country: { id: 5, nameEn: 'Japan', code: 'JP' },
    _count: { comments: 5 },
  },
  {
    id: '2',
    userId: 'user-2',
    countryId: 3,
    categoryId: 2,
    title: 'Bread is a serious matter',
    content: 'Germans take their bread very seriously - there are over 300 types of bread in Germany. Bakeries are everywhere and fresh bread is a daily ritual. Don\'t be surprised if people have strong opinions about proper bread.',
    experienceType: 'lived',
    likesCount: 18,
    dislikesCount: 1,
    commentsCount: 3,
    isPublished: true,
    isReported: false,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    user: { id: 'user-2', email: 'user2@example.com' },
    category: { id: 2, nameEn: 'Food Culture', icon: '🍽️' },
    country: { id: 3, nameEn: 'Germany', code: 'DE' },
    _count: { comments: 3 },
  },
  {
    id: '3',
    userId: 'user-3',
    countryId: 5,
    categoryId: 4,
    title: 'Silence is normal',
    content: 'In Japan, silence in a conversation isn\'t awkward, it\'s normal. People take time to think before speaking. Took me months to stop trying to fill every gap with words.',
    experienceType: 'lived',
    likesCount: 31,
    dislikesCount: 1,
    commentsCount: 8,
    isPublished: true,
    isReported: false,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
    user: { id: 'user-3', email: 'user3@example.com' },
    category: { id: 4, nameEn: 'Manners & Etiquette', icon: '🤝' },
    country: { id: 5, nameEn: 'Japan', code: 'JP' },
    _count: { comments: 8 },
  },
]

export const mockComments = [
  {
    id: '1',
    postId: '1',
    userId: 'user-3',
    parentCommentId: null,
    content: 'I experienced this firsthand! The train system is incredibly precise.',
    likesCount: 5,
    dislikesCount: 0,
    isReported: false,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
]

export const USE_MOCK_DATA = true // Toggle this when database is available
